# ZareonGuild - config.yml
# All MiniMessage-formatted texts here will be parsed in GUIs and system messages.
# Economy and level costs rely on Vault if present.

economy:
  enabled: true
  rename_cost: 1000.0 # money required to rename a guild
  level_costs:
    "2":
      money: 2500.0
      resources:
        - "DIAMOND:8"
        - "OBSIDIAN:64"
    "3":
      money: 5000.0
      resources:
        - "NETHERITE_INGOT:2"
        - "OBSIDIAN:64"
    "4":
      money: 10000.0
      resources:
        - "NETHERITE_INGOT:4"
        - "CRYING_OBSIDIAN:32"
    "5":
      money: 20000.0
      resources:
        - "NETHER_STAR:1"
        - "ANCIENT_DEBRIS:16"

ranks:
  order: [BEGINNER, VETERAN, MASTER, RIGHT_HAND, LEADER]
  permissions:
    BEGINNER:
      invite: false
      promote: false
      demote: false
      disband: false
      rename: false
      place_blocks: true
      place_tnt: true
      manage_flags: false
    VETERAN:
      invite: true
      promote: false
      demote: false
      disband: false
      rename: false
      place_blocks: true
      place_tnt: true
      manage_flags: false
    MASTER:
      invite: true
      promote: true
      demote: true
      disband: false
      rename: false
      place_blocks: true
      place_tnt: true
      manage_flags: false
    RIGHT_HAND:
      invite: true
      promote: true
      demote: true
      disband: false
      rename: true
      place_blocks: true
      place_tnt: true
      manage_flags: false
    LEADER:
      invite: true
      promote: true
      demote: true
      disband: true
      rename: true
      place_blocks: true
      place_tnt: true
      manage_flags: true

levels:
  min: 1
  max: 5
  gating:
    blocks:
      lv1: 1
      lv3: 3
      lv4: 4
    tnt:
      small: 2
      medium: 3
      large: 5

blocks:
  # Private block definitions; supports VANILLA and ITEMSADDER.
  # Each block creates a protected region centered at the block with a radius (Manhattan cube).
  lv1:
    display: "<green>Small Guild Core"
    type: VANILLA
    id: BEACON
    radius: 8
  lv3:
    display: "<yellow>Medium Guild Core"
    type: VANILLA
    id: LODESTONE
    radius: 16
  lv4:
    display: "<gold>Large Guild Core"
    type: ITEMSADDER
    id: zareon:guild_core_large
    radius: 24

tnt:
  # TNT tiers; crafting is allowed only if guild level >= required
  small:
    display: "<yellow>Small Guild TNT"
    power: 6.0
    break_obsidian: true
    break_water: true
    recipe:
      shape: [ "GSG", "SFS", "GSG" ]
      ingredients:
        G: GUNPOWDER
        S: SAND
        F: FLINT
  medium:
    display: "<gold>Medium Guild TNT"
    power: 9.0
    break_obsidian: true
    break_water: true
    recipe:
      shape: [ "GSG", "SNG", "GSG" ]
      ingredients:
        G: GUNPOWDER
        S: SAND
        N: NETHER_BRICK
  large:
    display: "<red>Large Guild TNT"
    power: 12.0
    break_obsidian: true
    break_water: true
    recipe:
      shape: [ "GSG", "SDS", "GSG" ]
      ingredients:
        G: GUNPOWDER
        S: SAND
        D: DIAMOND

flags:
  # Server admin only (no in-game edits). Detailed comments here.
  # Whether PvP is allowed inside guild regions.
  pvp: false
  # Whether explosions (non-guild TNT) are allowed in regions.
  explosions: false
  # Whether mobs can spawn in regions.
  mob_spawn: true
  # Whether players can build (non-members denied).
  build: false
  # Whether chest access by non-members is allowed.
  chest_access: false
  # Whether redstone works (if false, some devices may be disabled).
  redstone: true

gui:
  menu:
    title: "<gradient:#00E1FF:#00FF88>Guild Menu</gradient>"
    size: 54
    layout:
      members_start_slot: 10
      members_per_row: 7
    items:
      filler:
        material: GRAY_STAINED_GLASS_PANE
        name: "<gray>-</gray>"
      promote:
        material: LIME_DYE
        name: "<green>Promote</green>"
        lore:
          - "<gray>Increase member rank</gray>"
      demote:
        material: RED_DYE
        name: "<red>Demote</red>"
        lore:
          - "<gray>Decrease member rank</gray>"
      level_up:
        material: EXPERIENCE_BOTTLE
        name: "<gold>Level Up Guild</gold>"
        lore:
          - "<gray>Spend money and resources</gray>"
      regions:
        material: AMETHYST_SHARD
        name: "<light_purple>Your Regions</light_purple>"
        lore:
          - "<gray>List and place blocks</gray>"
      flags:
        material: TARGET
        name: "<yellow>Flags</yellow>"
        lore:
          - "<gray>View region flags</gray>"
      tnt:
        material: TNT
        name: "<red>Guild TNT</red>"
        lore:
          - "<gray>Recipes & crafting</gray>"
