name: ZareonGuild
version: 1.0.0
main: com.zareon.guild.ZareonGuildPlugin
api-version: '1.21'
authors: [ Zareon ]
description: Guilds with levels, private blocks, TNT tiers, GUI and Vault economy.
softdepend:
  - Vault
  - PlaceholderAPI
  - ItemsAdder
  - WorldGuard
  - WorldEdit
commands:
  guild:
    description: ZareonGuild main command
    usage: /guild help
    permission: zareonguild.command

permissions:
  zareonguild.command:
    default: true
